### PR TITLE
Vectorize Rejection Sampling

### PR DESCRIPTION
**Pull request by cothan**
[//]: # (SPDX-License-Identifier: CC-BY-4.0)
[//]: # (TODO Customize PR template)

# Improve the performance of Rejection Sampling

I have not benchmark this code, this code is refactored and cleaned up from my previous implementation of Kyber.

It's seem like we need to switch to CircleCI to have ARM-based runner. 

[//]: # (See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository )

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)

### CODE REVIEW

**Comment by cothan** [comment]
I tried to rewrite the sampler to meet the layout of Keccak. 
It's seem like we can't use the layout friendly to Keccak, this make the loading from sampling very difficult. 

The sample will need 3 bytes, to produce 2 coefficients. 

If we layout like this:

`0 - 1 - 2 -3 - 4 - 5 -6 - 7 | 8 - 9 - a - b - c - d - e - f`.

With `0 -> to 7` belongs to `keccak_way_1` and `8->f` belongs `keccak_way_2`, then it's not possible to align the byte we need:

Bytes: `0, 1, 2`, `3, 4, 5` create 4 coeffcients. Missing one byte added to `6, 7` to complete the sampling.

Similarly, `keccak_way_2` also needs one additional byte to complete the sampling. 

Thus, the memory layout of Keccak must be `All data of keccak_way_1 || All data of keccak_way_2 || ...` The interleave will make the sampler more difficult.

**Comment by cothan** [comment]
We need ARM-runner so build_test can run.  #34

**Comment by mkannwischer** [comment]
We can just cross compile and emulate using qemu. 
See for example here: https://github.com/slothy-optimizer/pqax/blob/main/.github/workflows/tests.yaml. 
Do you mind setting that up? We won't have Arm runners any time soon.

**Comment by cothan** [comment]
I have a tight schedule this week. Perhaps next week I'll set it up.

**Comment by hanno-becker** [comment]
@cothan @mkannwischer This PR reminds me that we should discuss intrinsics vs. ASM.

As hinted at in the README, my preference is to write 'clean' ASM and automatically micro-optimize it, e.g. using SLOTHY. The main reasons are: (1) _Assurance:_ There is more tooling for the verification of ASM than Intrinsics, at least to my knowledge. Moreover, verification can be split into separate verification of the clean code and the micro-optimizations. (2) _Performance:_ Past experience shows that the best implementations are obtained by writing ASM by hand. Moreover, by splitting development into manual writing of clean code and automatic micro-optimization, development time should not be much higher than when writing intrinsics (This may be false in general if there are a lot of stack spills, but this is not the case for MLKEM).

I would therefore propose that we do not use intrinsics but clean ASM throughout, including this PR. @cothan Would you be willing to port your intrinsics code to ASM? Might be a useful learning experience as well.

Thoughts?

**Comment by cothan** [comment]
Hi @hanno-becker , 

Good idea. Originally this function was implemented in Intrinsic since it's quicker for me to debug in my VSCode. I Don't mind writing ASM at all. I will port this implementation to ASM. Do we have a Python template to generate ASM that I can take look at?

**Comment by hanno-becker** [comment]
@cothan I tend to write ASM by hand, but making extensive use of `.req` and `.macro` directives to keep things modular and readable. We have plenty of examples in the [SLOTHY](https://github.com/slothy-optimizer/slothy) repo.

**Comment by cothan** [comment]
Update: I have my ASM working and will update this PR very soon!

**Comment by hanno-becker** [comment]
Awesome @cothan !

**Comment by cothan** [comment]
Oh, with macos-latest I thought it will run on arm64. But it's not.

**Pull request closed without merging**
