### PR TITLE
Fix variable detection of recursive make

### LINKED ISSUE #114: The `--cflags` parameter in the `tests` script does not work
I observe the following behaviour:

```
> nix develop --experimental-features 'nix-command flakes' .#ci
$ tests nistkat
... (* OK *)
$ tests nistkat --cflags "-DSOMETHING_IRRELEVANT" 
...
INFO  > Nistkat Test
INFO  > CFLAGS=-DSOMETHING_IRRELEVANT make CROSS_PREFIX=  nistkat
test/gen_NISTKAT.c:33:5: error: call to undeclared function 'nist_kat_init'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    nist_kat_init(entropy_input, NULL, 256);
    ^
test/gen_NISTKAT.c:62:9: error: call to undeclared function 'nist_kat_init'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        nist_kat_init(seed, NULL, 256);
        ^
2 errors generated.
make[1]: *** [mk/rules.mk:22: test/build/mlkem512/test/gen_NISTKAT.c.o] Error 1
```

Digging a bit, it looks like the default `CFLAGS` is overwritten, not amended.

### PR DESCRIPTION
**Pull request by potsrevennil**
Fix  #114

### CODE REVIEW

**Comment by hanno-becker** [comment]
@potsrevennil I still get the same error when trying `tests nistkat --cflags "-DSOMETHING_IRRELEVANT"`

**Comment by hanno-becker** [comment]
I don't think this is specific to RNG, but to the entire CFLAGS from `config.mk` being overwritten.

**Comment by potsrevennil** [comment]
Thanks for the check, did a more thoroughly check. Seems like there are some other minor issues  caused by recursive make happening as well. 
For example, CFLAGS is in fact re-appended everytime when make recursively. There are some caveats in recursive make, so in general I should try to avoid using it when possible. 😭

**Comment by hanno-becker** [comment]
@potsrevennil It all seems to work now, thank you 🙏

**Review by hanno-becker — APPROVED** [review]

**Pull request merged**
