### PR TITLE
CBMC: Add specs and proofs for poly_getnoise_xxx

### LINKED ISSUE #310: CBMC: State + prove specs for `poly_getnoise_xxx()`
Depends on: https://github.com/pq-code-package/mlkem-c-aarch64/issues/309

### PR DESCRIPTION
**Pull request by hanno-becker**
Resolves #310 

Based on #313 

Noteworthy: This PR _axiomatizes_ the behaviour of `shake256x4` and `mlkem_sha256_prf` until we have proof.

### CODE REVIEW

**Review by mkannwischer — CHANGES_REQUESTED** [review]
I believe this has the same mistakes in the bounds as #313. Please first resolve that, then I will review this again.

**Review by mkannwischer — CHANGES_REQUESTED** [review]
The bounds look good now, but I think you missed `poly_getnoise_eta1122_4x`

**Comment by hanno-becker** [comment]
@mkannwischer daone

**Review by mkannwischer — APPROVED** [review]
Thanks for all the edits! Now this looks good.

**Pull request merged**
