### PR TITLE
Add proof of poly_compress()

### PR DESCRIPTION
**Pull request by rod-chapman**
This PR adds contracts and CBMC proof of type safety for the poly_compress() function in poly.c

Both variants of the code are covered, depending on the value of KYBER_K.

For example,
```
cd cbmc/proofs/poly_compress
make KYBER_K=3
make KYBER_K=4
```
to reproduce proofs of both variants.

### CODE REVIEW

**Comment by hanno-becker** [comment]
@rod-chapman What's the status of this?

**Comment by rod-chapman** [comment]
Waiting for Issue #94 I think. "astyle" still breaks everything on my branch, so the "lint" runner fails.

**Comment by hanno-becker** [comment]
I will try to reproduce.

**Comment by hanno-becker** [comment]
I can reproduce the issue locally. 
```
> nix develop --experimental-features 'nix-command flakes' .#ci-linter
> lint
```

**Comment by hanno-becker** [comment]
@rod-chapman Rebased on `main`

**Review by hanno-becker — APPROVED** [review]
LGTM -- Thanks @rod-chapman!

**Pull request merged**
