### PR TITLE
Rename Kyber -> ML-KEM

### LINKED ISSUE #247: Rename Kyber -> ML-KEM everywhere

### PR DESCRIPTION
**Pull request by mkannwischer**
Resolves #247 
This PR renames Kyber to ML-KEM everywhere to make it a little less confusing. 

The only place I have not changed is the following as that changes testvectors: https://github.com/pq-code-package/mlkem-c-aarch64/blob/3f579b25f33f726e5119cd0afad3df840b6268a8/mlkem/kem.h#L14
Do we want to change that as well? Then we either need to update the testvectors, or somehow pass the `ALGNAME` from outside for that test.

### CODE REVIEW

**Comment by mkannwischer** [comment]
I don't understand why this PR did not trigger CI.

**Comment by hanno-becker** [comment]
I don't, either. Can you force-push a 0-diff to see if it's spurious?

**Review by hanno-becker — COMMENTED** [review]
LGTM, reproduced this locally and confirmed that no unwanted instances of "Kyber" remain.

**Comment by hanno-becker** [comment]
> I don't understand why this PR did not trigger CI.

#263

**Review by hanno-becker — APPROVED** [review]

**Pull request merged**
