### PR TITLE
cbmc: Move contracts to separate header

### PR DESCRIPTION
**Pull request by hanno-becker**
CBMC annotations should be organized so that they clutter the main code base as little as possible.

This commit moves the CBMC specs written so far from `poly.h` into a new header `poly_specs.h` that's in the `cbmc/` subdirectory, keeping the original `poly.h` from the reference implementation.

An alternative could be to make the annotations less cryptic by introducing abbreviations like

```
    #define CONTRACT_ASSERT(...)      __CPROVER_assert(__VA_ARGS__)
    #define CONTRACT_ASSIGNS(...)     __CPROVER_assigns(__VA_ARGS__)
    #define CONTRACT_ASSIGNS_ERR(...) CONTRACT_ASSIGNS(__VA_ARGS__, _s2n_debug_info, s2n_errno)
    #define CONTRACT_ASSUME(...)      __CPROVER_assume(__VA_ARGS__)
    #define CONTRACT_REQUIRES(...)    __CPROVER_requires(__VA_ARGS__)
    #define CONTRACT_ENSURES(...)     __CPROVER_ensures(__VA_ARGS__)
    #define CONTRACT_INVARIANT(...)   __CPROVER_loop_invariant(__VA_ARGS__)
    #define CONTRACT_RETURN_VALUE     (__CPROVER_return_value)
    #define CONTRACT_ASSERT(...)
    #define CONTRACT_ASSIGNS(...)
    #define CONTRACT_ASSIGNS_ERR(...)
    #define CONTRACT_ASSUME(...)
    #define CONTRACT_REQUIRES(...)
    #define CONTRACT_ENSURES(...)
    #define CONTRACT_INVARIANT(...)
    #define CONTRACT_RETURN_VALUE
```

which is the approach taken by
s2n-tls (https://github.com/aws/s2n-tls/blob/ff610637368c31ef7bea5e3e5814c30af64263de/utils/s2n_ensure.h#L130).

[//]: # (SPDX-License-Identifier: CC-BY-4.0)

### CODE REVIEW

**Comment by hanno-becker** [comment]
Request for comments, @rod-chapman @mkannwischer.

This does not only concern the specs, but also the proofs, which often rely on loop invariants being annotated in the C source. See Rod's recent PR #161.

With the present approach, I feel that the CBMC annotations do clutter the code significantly, and are cryptic to readers. Wrapping them more palatable abbreviations as above might help, though I'm currently inclined to keep CBMC annotations out of the main code base altogether, by (a) moving specs into a separate header as done here, (b) wrapping annotations into single macros like `XXX_LOOP_INVARIANT`.

Let's discuss.

**Comment by hanno-becker** [comment]
If one abbreviates all the `__CPROVER_...` macros, things become much more readable:
```
void poly_compress(uint8_t r[KYBER_POLYCOMPRESSEDBYTES], const poly *a)
{
    uint8_t t[8] = { 0 };

    const size_t num_blocks = KYBER_N / 8;

    #if (KYBER_POLYCOMPRESSEDBYTES == 128)
    for (size_t i = 0; i < num_blocks; i++)
        ASSIGNS(i, OBJ(t), OBJ(r))
        INVARIANT(i <= num_blocks)
        DECREASES(num_blocks - i)
    {
        for (size_t j = 0; j < 8; j++)
            ASSIGNS(j, OBJ(t))
            INVARIANT(i <= num_blocks)
            INVARIANT(j <= 8)
            INVARIANT(FORALL { size_t k2; (0 <= k2 && k2 < j) ==> (t[k2] >= 0 && t[k2] < 16) })
            DECREASES(8 - j)
        {
            // map to positive standard representatives
            // REF-CHANGE: Hoist signed-to-unsigned conversion into separate function
            int32_t u;
            u = (int32_t) scalar_signed_to_unsigned_q_16(a->coeffs[8 * i + j]);
            // REF-CHANGE: Hoist scalar compression into separate function
            t[j] = scalar_compress_q_16(u);
        }

        // REF-CHANGE: Use array indexing into
        // r rather than pointer-arithmetic to simplify verification
        r[i * 4]     = t[0] | (t[1] << 4);
        r[i * 4 + 1] = t[2] | (t[3] << 4);
        r[i * 4 + 2] = t[4] | (t[5] << 4);
        r[i * 4 + 3] = t[6] | (t[7] << 4);
    }
    #elif (KYBER_POLYCOMPRESSEDBYTES == 160)
    for (size_t i = 0; i < num_blocks; i++)
        ASSIGNS(i, OBJ(t), OBJ(r))
        INVARIANT(i <= num_blocks)
        DECREASES(num_blocks - i)
    {
        for (size_t j = 0; j < 8; j++)
            ASSIGNS(j, OBJ(t))
            INVARIANT(i <= num_blocks)
            INVARIANT(j <= 8)
            INVARIANT(FORALL { size_t k2; (0 <= k2 && k2 < j) ==> (t[k2] >= 0 && t[k2] < 32) })
            DECREASES(8 - j)
        {
            // map to positive standard representatives
            // REF-CHANGE: Hoist signed-to-unsigned conversion into separate function
            int32_t u = (int32_t) scalar_signed_to_unsigned_q_16(a->coeffs[8 * i + j]);
            // REF-CHANGE: Hoist scalar compression into separate function
            t[j] = scalar_compress_q_32(u);
        }

        // REF-CHANGE: Explicitly truncate to avoid warning about
        // implicit truncation in CBMC, and use array indexing into
        // r rather than pointer-arithmetic to simplify verification
        r[i * 5]     = 0xFF & ((t[0] >> 0) | (t[1] << 5));
        r[i * 5 + 1] = 0xFF & ((t[1] >> 3) | (t[2] << 2) | (t[3] << 7));
        r[i * 5 + 2] = 0xFF & ((t[3] >> 1) | (t[4] << 4));
        r[i * 5 + 3] = 0xFF & ((t[4] >> 4) | (t[5] << 1) | (t[6] << 6));
        r[i * 5 + 4] = 0xFF & ((t[6] >> 2) | (t[7] << 3));
    }
```

**Comment by rod-chapman** [comment]
1. Abbreviating the contracts with macros - yes - absolutely agree. The default syntax is ugly and verbose.
2. There are common "patterns" emerging (such as all elements of this array are in range a .. b") that could be further abbreviated with macros.
3. As for moving the contracts into a separate file... I feel this is unwise. Let's talk.

**Comment by hanno-becker** [comment]
Closing this for now -- let's see first how far we get with abbreviations (cf. #169)

**Pull request closed without merging**
